---
title: "Statistika Non Parametrik"
author: "Wulan"
date: "2024-11-10"
output: html_document
---

# STATISTIKA NON PARAMETRIK

### Uji Friedman

```{r}
# Menyiapkan data
data <- data.frame(subject = factor(rep(1:5,
each=3)),condition = factor(rep(c("Perawatan 1", "Perawatan
2", "Perawatan 3"), times=5)),
 score =
c(12,15,14,13,16,12,10,14,13,11,15,14,12,17,15))
#boxplot
boxplot(data$score~data$condition, border = "black",col=
c("blue", "green", "red","orange"))

```

```{r}
friedman_test <- friedman.test(score ~ condition | subject,
data = data)
print(friedman_test)

```

```{r}
library(PMCMRplus)
#Perbandingan Berganda
frdAllPairsNemenyiTest(data$score, data$condition,data$subject)
```

### Tabel Kontingensi

```{r}
#tabel kontingensi 2xk
# Membuat tabel kontingensi
data <- matrix(c(30, 20, 50,40, 30, 20), nrow = 2, byrow = TRUE)
# Memberi nama baris dan kolom
rownames(data) <- c("Pria", "Wanita")
colnames(data) <- c("Produk1", "Produk2", "Produk3")
# Tampilkan tabel kontingensi
print(data)
# Melakukan uji chi-square
chi_square_test <- chisq.test(data)
# Menampilkan hasil
print("Hasil Uji Chi-Square:")
print(chi_square_test)
```

```{r}
# Memeriksa frekuensi yang diharapkan
expected_frequencies <- chi_square_test$expected
print("Frekuensi yang Diharapkan:")
print(expected_frequencies) 
```

### Uji Normalitas

```{r}
# Uji Kolmogorov-Smirnov
data<-c(2,3,5,6,3,2,9,7,8,6,8,5,2,4,5,4,3,1,8,7)
install.packages("nortest")
library(nortest)
ks.test(data,"pnorm", mean(data), sd(data))
```

```{r}
# Uji Liliefors
data<-c(2,3,5,6,3,2,9,7,8,6,8,5,2,4,5,4,3,1,8,7)
library(nortest)
lillie.test(data)
```

```{r}
# Uji Homogenitas
bartlett.test(Petal.Length ~ Species, data = iris)
```

```{r}
install.packages("nortest", repos = "https://cran.r-project.org")
```

